export const CONNECTED = 'CONNECTED';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const CONNECTED_USERS = 'CONNECTED_USERS';
export const ADD_CONNECTED_USER = 'ADD_CONNECTED_USERS';
export const REMOVE_CONNECTED_USER = 'REMOVE_CONNECTED_USER';

export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
